### ISSUE TITLE
`plugin rsync` and only one file (selected or hovered) doesn't work

### ISSUE THREAD

**Issue by xfzv** [GianniBYoung/rsync.yazi#1]
With:

```toml
[[manager.prepend_keymap]]
on = ["R"]
run = "plugin rsync"
desc = "Copy files using rsync"
```

If I select multiple files and press `R`: no issue, the prompt is showing up and I can manually type `[user]@[remote]:<destination>`.

However, if I select only one file or hover a file and press `R`, the task is stuck at 99% and the following error is displayed in task manager:

```console
Micro plugin failed:
runtime error: [string "rsync"]:33: attempt to concatenate a nil value (local 'remote_target')
stack traceback:
	[string "rsync"]:33: in function <[string "rsync"]:21>
```

Note that

```toml
[[manager.prepend_keymap]]
on = ["R"]
run = "plugin rsync --args='user@server.com'"
desc = "Copy files using rsync to default location"
```

works just fine even if selecting/hovering a single file.

---

```console
% cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.15"

% yazi -V
Yazi 0.3.1 (99a3b3a 2024-08-16)

% rsync --version
rsync  version 3.3.0  protocol version 31
```
